# Importing numpy library

In [2]:
import numpy as np


# Numpy array

In [5]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


# Dimension of numpy array

In [6]:
a.ndim

2

# Byte size of each element

In [7]:
a.itemsize

4

# Find the datatype

In [8]:
a.dtype

dtype('int32')

# Size of  the array

In [9]:
a.size

6

# Shape of the array

In [10]:
a.shape

(2, 3)

# Reshape from the original shape

In [11]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

# Slicing

In [12]:
a=np.array([[1,2,3,4],[5,4,6,8],[2,6,9,4]])
print(a[0,2])

3


In [13]:
print(a[:,3])

[4 8 4]


In [16]:
print(a[:2,3])

[4 8]


In [18]:
a=np.linspace(1,3,10)
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


# Maximum

In [ ]:
a.max()

# Minimum

In [20]:
a.min()

1.0

# Sum

In [21]:
a.sum()

20.0

# Axis

In [23]:
a=np.array([[1,2,3,4],[5,4,6,8]])
print(a.sum(axis=0))       #column

[ 6  6  9 12]


In [24]:
a.sum(axis=1)  #row

array([10, 23])

# Square root

In [25]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.        , 2.44948974, 2.82842712]])

# Standard Deviation

In [26]:
np.std(a)

2.0879116360612584

# Arithmetic operation

In [27]:
a=np.array([[1,2,3,4],[5,4,6,8]])
b=np.array([[1,2,3,4],[5,4,6,8]])
print(a+b)

[[ 2  4  6  8]
 [10  8 12 16]]


In [28]:
print(a-b)

[[0 0 0 0]
 [0 0 0 0]]


In [29]:
print(a*b)

[[ 1  4  9 16]
 [25 16 36 64]]


In [30]:
print(a/b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Vertical Stack

In [31]:
print(np.vstack((a,b)))

[[1 2 3 4]
 [5 4 6 8]
 [1 2 3 4]
 [5 4 6 8]]


# Horizontal stack

In [32]:
print(np.hstack((a,b)))

[[1 2 3 4 1 2 3 4]
 [5 4 6 8 5 4 6 8]]


# Exponential

In [33]:
a=np.array([1,2,3])
print(np.exp(a))

[ 2.71828183  7.3890561  20.08553692]


# Logarithmic 

In [34]:
print(np.log(a))

[0.         0.69314718 1.09861229]


In [35]:
print(np.log10(a))

[0.         0.30103    0.47712125]


# Zeros

In [36]:
np.zeros(3)

array([0., 0., 0.])

In [38]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# Ones

In [40]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [41]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
np.zeros(5)+5

array([5., 5., 5., 5., 5.])

# Eye

In [44]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Randn

In [46]:
np.random.randn(5)  #include negative value

array([ 0.07228097,  0.07605189,  0.20504791, -0.84910032,  0.58317379])

In [49]:
np.random.randn(4,3)

array([[ 0.0320834 , -0.69923647,  1.29073622],
       [-1.26458276,  0.13168575,  1.93716865],
       [-1.17147963, -1.17600525,  1.13532536],
       [ 0.77564156, -0.24183608, -1.98279817]])

# Rand

In [50]:
np.random.rand(3)

array([0.51891377, 0.34576339, 0.47225666])

In [51]:
np.random.rand(3,4)

array([[0.9070949 , 0.09547702, 0.80466336, 0.91889521],
       [0.66852454, 0.90449133, 0.79959973, 0.31025195],
       [0.65919182, 0.65514003, 0.87620176, 0.2451565 ]])

In [53]:
np.random.randint(1,10)

8

In [56]:
a=np.random.randint(1,10,5)

In [57]:
a

array([7, 4, 6, 3, 5])

# Index of max value

In [58]:
a.argmax()

0

# Index of min value

In [59]:
a.argmin()

3

# Indexing and Selection

In [67]:
arr=np.arange(10,40,2).reshape(3,5)

In [68]:
arr

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [69]:
arr[1:,1:3]

array([[22, 24],
       [32, 34]])

In [70]:
arr[:,1:2]

array([[12],
       [22],
       [32]])

In [79]:
arr=np.arange(1,10,2)

In [80]:
arr

array([1, 3, 5, 7, 9])

In [81]:
arr+arr

array([ 2,  6, 10, 14, 18])

In [83]:
print(arr-arr)
print(arr*arr)
print(arr/arr)

[0 0 0 0 0]
[ 1  9 25 49 81]
[1. 1. 1. 1. 1.]


# Sin

In [85]:
x=np.arange(1,10,2)
np.sin(x)

array([ 0.84147098,  0.14112001, -0.95892427,  0.6569866 ,  0.41211849])

# cos

In [86]:
np.cos(x)

array([ 0.54030231, -0.9899925 ,  0.28366219,  0.75390225, -0.91113026])

# Tan

In [88]:
np.tan(x)

array([ 1.55740772, -0.14254654, -3.38051501,  0.87144798, -0.45231566])